In [1]:
import os
os.chdir(r'C:\Users\Nageswar\Desktop\hire hack')

In [2]:
import numpy as np
import pandas as pd
data=pd.read_csv('test.csv')

In [3]:
data

angle(X,gravityMean)  angle(Y,gravityMean)  angle(Z,gravityMean)  \
0                -0.720009              0.276801             -0.057978   
1                -0.698091              0.281343             -0.083898   
2                -0.702771              0.280083             -0.079346   
3                -0.698954              0.284114             -0.077108   
4                -0.692245              0.290722             -0.073857   
5                -0.689816              0.294896             -0.068471   
6                -0.690085              0.295282             -0.067065   
7                -0.688785              0.295981             -0.067706   
8                -0.685390              0.299394             -0.065491   
9                -0.684110              0.300822             -0.064263   
10               -0.686013              0.298478             -0.066625   
11               -0.685710              0.297687             -0.069092   
12               -0.683619              0.299401             -0.068704   
13               -0.680503              0.302289             -0.067274   
14               -0.674944              0.306351             -0.067373   
15               -0.672948              0.306460             -0.070759   
16               -0.591690              0.379258             -0.004655   
17               -0.598653              0.374095             -0.008468   
18               -0.594755              0.377131             -0.004721   
19               -0.601416              0.371978             -0.010461   
20               -0.595470              0.375913             -0.012193   
21               -0.579426              0.387695             -0.005265   
22               -0.573604              0.391731             -0.005176   
23               -0.587638              0.379843             -0.023736   
24               -0.601530              0.368305             -0.034342   
25               -0.604059              0.367321             -0.030170   
26               -0.600177              0.371195             -0.023182   
27               -0.596625              0.374298             -0.018806   
28               -0.597761              0.373296             -0.020333   
29               -0.598912              0.372410             -0.020935   
...                    ...                   ...                   ...   
2917             -0.694649              0.245906              0.172715   
2918             -0.722767              0.244779              0.144695   
2919             -0.694613              0.259140              0.157683   
2920             -0.671194              0.265751              0.174766   
2921             -0.661045              0.270618              0.179726   
2922             -0.657085              0.276184              0.177337   
2923             -0.663506              0.273305              0.173953   
2924             -0.660163              0.274327              0.176291   
2925             -0.652636              0.277868              0.180047   
2926             -0.656760              0.271648              0.182987   
2927             -0.657011              0.266990              0.187901   
2928             -0.807271              0.189885              0.118456   
2929             -0.814760              0.190418              0.110325   
2930             -0.809277              0.192232              0.113997   
2931             -0.809257              0.185954              0.120358   
2932             -0.800932              0.190968              0.123600   
2933             -0.803888              0.191732              0.119944   
2934             -0.810091              0.184712              0.120724   
2935             -0.797719              0.194819              0.122937   
2936             -0.803914              0.196823              0.114498   
2937             -0.691122              0.241953              0.180141   
2938             -0.677946              0.256877              0.177768   
2939      

In [4]:
data['Activity'].replace(['LAYING','STANDING','WALKING','SITTING','WALKING_UPSTAIRS','WALKING_DOWNSTAIRS'],['0','1','00','11','000','111'],inplace=True)

In [5]:
x=data.iloc[:,0:3]
y=data.iloc[:,3]

In [6]:
x

angle(X,gravityMean)  angle(Y,gravityMean)  angle(Z,gravityMean)
0                -0.720009              0.276801             -0.057978
1                -0.698091              0.281343             -0.083898
2                -0.702771              0.280083             -0.079346
3                -0.698954              0.284114             -0.077108
4                -0.692245              0.290722             -0.073857
5                -0.689816              0.294896             -0.068471
6                -0.690085              0.295282             -0.067065
7                -0.688785              0.295981             -0.067706
8                -0.685390              0.299394             -0.065491
9                -0.684110              0.300822             -0.064263
10               -0.686013              0.298478             -0.066625
11               -0.685710              0.297687             -0.069092
12               -0.683619              0.299401             -0.068704
13               -0.680503              0.302289             -0.067274
14               -0.674944              0.306351             -0.067373
15               -0.672948              0.306460             -0.070759
16               -0.591690              0.379258             -0.004655
17               -0.598653              0.374095             -0.008468
18               -0.594755              0.377131             -0.004721
19               -0.601416              0.371978             -0.010461
20               -0.595470              0.375913             -0.012193
21               -0.579426              0.387695             -0.005265
22               -0.573604              0.391731             -0.005176
23               -0.587638              0.379843             -0.023736
24               -0.601530              0.368305             -0.034342
25               -0.604059              0.367321             -0.030170
26               -0.600177              0.371195             -0.023182
27               -0.596625              0.374298             -0.018806
28               -0.597761              0.373296             -0.020333
29               -0.598912              0.372410             -0.020935
...                    ...                   ...                   ...
2917             -0.694649              0.245906              0.172715
2918             -0.722767              0.244779              0.144695
2919             -0.694613              0.259140              0.157683
2920             -0.671194              0.265751              0.174766
2921             -0.661045              0.270618              0.179726
2922             -0.657085              0.276184              0.177337
2923             -0.663506              0.273305              0.173953
2924             -0.660163              0.274327              0.176291
2925             -0.652636              0.277868              0.180047
2926             -0.656760              0.271648              0.182987
2927             -0.657011              0.266990              0.187901
2928             -0.807271              0.189885              0.118456
2929             -0.814760              0.190418              0.110325
2930             -0.809277              0.192232              0.113997
2931             -0.809257              0.185954              0.120358
2932             -0.800932              0.190968              0.123600
2933             -0.803888              0.191732              0.119944
2934             -0.810091              0.184712              0.120724
2935             -0.797719              0.194819              0.122937
2936             -0.803914              0.196823              0.114498
2937             -0.691122              0.241953              0.180141
2938             -0.677946              0.256877              0.177768
2939             -0.672635              0.261034              0.178609
2940             -0.660366              0.272243              0.178547
2941             -0.646754    

In [7]:
y

0         1
1         1
2         1
3         1
4         1
5         1
6         1
7         1
8         1
9         1
10        1
11        1
12        1
13        1
14        1
15        1
16        1
17        1
18        1
19        1
20        1
21        1
22        1
23        1
24        1
25        1
26        1
27        1
28        1
29        1
       ... 
2917    000
2918    000
2919    000
2920    000
2921    000
2922    000
2923    000
2924    000
2925    000
2926    000
2927    000
2928    111
2929    111
2930    111
2931    111
2932    111
2933    111
2934    111
2935    111
2936    111
2937    000
2938    000
2939    000
2940    000
2941    000
2942    000
2943    000
2944    000
2945    000
2946    000
Name: Activity, Length: 2947, dtype: object

In [8]:
from sklearn.model_selection import cross_validate,train_test_split,cross_val_score,cross_val_predict
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [9]:
y1_train=y_train.astype('int')
y1_train

877       0
1483    111
360       0
2119      0
2260     11
153       0
2572      1
2230      1
1619      0
2015      0
1251     11
1743     11
1108      0
1069      1
2768      1
2338      0
2265     11
244       0
1111      0
487       1
294       0
1698      1
1570     11
1761      0
919       1
29        1
1692      0
2214      1
2277     11
2513      0
       ... 
2340      0
62        0
1633      0
390       0
756       0
2210    111
1484    111
110     111
868     111
185      11
828       0
2944      0
1710      1
2430     11
2062      1
831       0
1887      1
875     111
1643    111
234       0
1632      0
152       0
1705      1
1868      1
2508      0
1724     11
1011      0
1182      0
2472      0
264     111
Name: Activity, Length: 2357, dtype: int32

In [10]:
from sklearn import preprocessing
minmax=preprocessing.MinMaxScaler(feature_range=(0,1))
minmax.fit(x).transform(x)

array([[0.14536648, 0.62209457, 0.46362736],
       [0.15742698, 0.62446791, 0.45014396],
       [0.15485148, 0.62380956, 0.45251181],
       ...,
       [0.1809411 , 0.62088108, 0.58803909],
       [0.17854107, 0.61581385, 0.59135763],
       [0.17834208, 0.61537208, 0.59163879]])

In [11]:
x_train_std=minmax.fit_transform(x_train)
x_test_std=minmax.fit_transform(x_test)
x_train_std

array([[0.17566385, 0.5114573 , 0.62800702],
       [0.09056211, 0.59275052, 0.51563395],
       [0.85196026, 0.12423002, 0.32548122],
       ...,
       [0.0871553 , 0.4638731 , 0.50234502],
       [0.79259529, 0.1409681 , 0.31580586],
       [0.17707076, 0.64221643, 0.45838087]])

In [12]:
from sklearn import neighbors
clf=neighbors.KNeighborsClassifier()
clf.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [13]:
y_pred=clf.predict(x_test)

In [14]:
y_test=y_test.astype('int')
y_test

2613     11
2297      0
592     111
2139      0
98        0
2331      0
52       11
2640      0
976       0
1571     11
210       0
2133      0
2846      0
2041      1
1915     11
2596      1
405       0
2224      1
318       1
381       0
842       0
2454     11
1460      0
1092     11
91        0
2726      0
1449      0
610       0
2413      1
1520      0
       ... 
722     111
2734      0
1817    111
1786      0
942      11
2242      1
2510      0
251       0
1192      0
43       11
705       0
2156    111
323       1
1308      0
1675      0
1058      1
1457      0
747     111
1885      1
46       11
96        0
618       0
1157      0
2800     11
200      11
2600     11
248       0
2749      0
269     111
1116      0
Name: Activity, Length: 590, dtype: int32

In [15]:
y_pred=y_pred.astype('int')
y_pred

array([ 11,   0, 111,   0,   0,   0,  11,   0,   0,  11,   0,   0,   0,
         1,  11, 111,   0,   1,  11,   0,   0,  11,   0,   1,   0,   0,
         0, 111,   0,   0,   0,  11,   0,   0,   0,   1,   0,   1,   0,
         0, 111,   0, 111,   0,   0,   0,  11,   0,   1,   0,  11,  11,
        11,   0,   0,   0,   1,   0,  11,   0,   0,   0,   0,   0,   0,
       111, 111,   1, 111,   0,   1,  11,  11,   0, 111, 111,   0, 111,
         0,   1, 111,   0,  11,   0,   0,   1, 111,   0,   0,   1,   0,
         0,  11,   0,   0,   0,   0, 111,   0,  11, 111, 111,   1,   0,
         0,   1,   0,  11,   0,   0,   0,  11,   1,   0,   0, 111,   0,
         0,   0, 111,  11,   0,   0,  11, 111, 111, 111,   0,   1,   1,
         1,   0,  11, 111,   0,   0,   1,   0,   0,   0,   0,   0,   1,
         0,   0,   0,  11,   1,  11,  11,   0,   1,   0,   1,  11,   0,
         1,   0,   0,  11,   0,   0,   1,   0,  11,   0,   0,  11,   0,
         0,  11,  11,   0,  11,   0,   0,   0,  11,   0,   1,  1

In [16]:
from sklearn.metrics import accuracy_score,recall_score,roc_auc_score,confusion_matrix
print("Accuracy Score : %f"%(accuracy_score(y_test,y_pred)*100)) #accuracy with knn classifier

Accuracy Score : 87.288136


In [17]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)
lr_acc=cross_val_score(lr,x_train_std,y_train,cv=3,scoring='accuracy',n_jobs=-1)
lr_proba=cross_val_predict(lr,x_train_std,y_train,cv=3,method='predict_proba')
lr_scores=lr_proba[:,1]

C:\Users\Nageswar\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Nageswar\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\Nageswar\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Nageswar\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\Nageswar\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarn

In [18]:
lr_acc #training, validation, testing


array([0.53231939, 0.54140127, 0.51340996])

In [19]:
y_pred=lr.predict(x_test)

In [20]:
y_test=y_test.astype('int')
y_test

2613     11
2297      0
592     111
2139      0
98        0
2331      0
52       11
2640      0
976       0
1571     11
210       0
2133      0
2846      0
2041      1
1915     11
2596      1
405       0
2224      1
318       1
381       0
842       0
2454     11
1460      0
1092     11
91        0
2726      0
1449      0
610       0
2413      1
1520      0
       ... 
722     111
2734      0
1817    111
1786      0
942      11
2242      1
2510      0
251       0
1192      0
43       11
705       0
2156    111
323       1
1308      0
1675      0
1058      1
1457      0
747     111
1885      1
46       11
96        0
618       0
1157      0
2800     11
200      11
2600     11
248       0
2749      0
269     111
1116      0
Name: Activity, Length: 590, dtype: int32

In [21]:
y_pred=y_pred.astype('int')
y_pred

array([ 11,   0,  11,   0,   1,   0,   1,   0,   0,   0,   0,   0,   0,
         0,  11,   1,  11,   1,  11,   0,   0,  11,   1,   1,   1,   0,
         0,   1,   0,   1,   0,   1,   0,   0,   1,   1,   0,  11,   1,
         0,   0,   1,   1,   1,   0,  11,  11,  11,   0,   0,  11,   1,
         1,   1,   0,   0,   1,   1,  11,   0,   0,   0,   0,   0,   1,
        11,   1,   0,   0,   0,   0,  11,  11,   0,   0,   0,   0,   0,
         0,   1,  11,  11,   0,   0,   0,  11,   0,   1,   0,   1,   0,
         1,  11,   1,   0,   1,   0,   0,   0,  11,   1,   1,   1,   0,
         1,   0,   0,   1,   0,   1,   0,  11,  11,   0,   0,   1,   0,
         0,   0,   1,  11,   0,   1,  11,   0,   1,   0,   0,  11,  11,
         1,   0,  11,  11,   0,   0,   0,   1,   1,   0,   1,   0,   1,
         0,   0,   1,  11,   0,  11,  11,   0,   1,   1,   1,  11,   0,
         0,   1,   0,   1,   1,  11,  11,   0,  11,   0,   0,   1,   0,
         0,  11,  11,   1,  11,   0,   1,   0,  11,   0,   1,  1

In [22]:
print("Accuracy Score : %f"%(accuracy_score(y_test,y_pred)*100)) #accuracy with logistic regression

Accuracy Score : 56.779661


In [23]:
from sklearn.svm import SVC
svc = SVC(kernel='rbf',probability = True)
svc_classifier = svc.fit(x_train,y_train)

C:\Users\Nageswar\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [24]:
svc_acc = cross_val_score(svc_classifier, x_train_std, y_train, cv=3, scoring="accuracy",  n_jobs=-1)
svc_proba = cross_val_predict(svc_classifier, x_train_std, y_train, cv=3, method='predict_proba')
svc_scores = svc_proba[:, 1]

C:\Users\Nageswar\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\Nageswar\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\Nageswar\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [26]:
y_pred=svc_classifier.predict(x_test)
y_pred=y_pred.astype('int')

In [27]:
print("\nAccuracy score: %f" %(accuracy_score(y_test,y_pred) * 100)) #svc classifier


Accuracy score: 55.932203


In [28]:
from sklearn.ensemble import RandomForestClassifier
rmf = RandomForestClassifier(max_depth=3, random_state=0)
rmf_clf = rmf.fit(x_train, y_train)

C:\Users\Nageswar\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [29]:
rmf_clf_acc = cross_val_score(rmf_clf, x_train_std, y_train, cv=3, scoring="accuracy",  n_jobs=-1)
rmf_proba = cross_val_predict(rmf_clf, x_train_std, y_train, cv=3, method='predict_proba')
rmf_clf_scores = rmf_proba[:, 1]

In [30]:
y_pred=lr.predict(x_test)
y_pred=y_pred.astype('int')

In [31]:
print("\nAccuracy score: %f" %(accuracy_score(y_test,y_pred) * 100)) #random forest classifier


Accuracy score: 56.779661


In [35]:
#Decision Tree Classifier
from sklearn.tree import DecisionTreeClassifier
dtc_clf = DecisionTreeClassifier()
dtc_clf.fit(x_train,y_train)

#Print cross validation score for Decision Tree Classifier
dtc_clf_acc = cross_val_score(dtc_clf, x_train_std, y_train, cv=3, scoring="accuracy",  n_jobs=-1)
dtc_proba = cross_val_predict(dtc_clf, x_train_std, y_train, cv=3, method='predict_proba')
dtc_clf_scores = dtc_proba[:, 1]

In [36]:
y_pred=dtc_clf.predict(x_test)
y_pred=y_pred.astype('int')

In [37]:
print("\nAccuracy score: %f" %(accuracy_score(y_test,y_pred) * 100)) #decision classifier


Accuracy score: 81.525424
