In [1]:
import os
os.chdir(r'C:\Users\Nageswar\Desktop\hire hack')

In [2]:
import numpy as np
import pandas as pd
data=pd.read_csv('test_2vd.csv')

In [3]:
data

fBodyAccMag-mean()  fBodyAccMag-std()            Activity
0              -0.790946          -0.711074            STANDING
1              -0.954127          -0.959746            STANDING
2              -0.975650          -0.983784            STANDING
3              -0.973393          -0.982120            STANDING
4              -0.977739          -0.978838            STANDING
5              -0.978002          -0.979876            STANDING
6              -0.984198          -0.987281            STANDING
7              -0.991349          -0.990767            STANDING
8              -0.993556          -0.990614            STANDING
9              -0.993693          -0.992943            STANDING
10             -0.993703          -0.993703            STANDING
11             -0.994000          -0.996011            STANDING
12             -0.992623          -0.995306            STANDING
13             -0.988634          -0.987937            STANDING
14             -0.987386          -0.989505            STANDING
15             -0.970842          -0.967468            STANDING
16             -0.862049          -0.855760            STANDING
17             -0.960538          -0.937976            STANDING
18             -0.983580          -0.972846            STANDING
19             -0.938897          -0.925589            STANDING
20             -0.937565          -0.945013            STANDING
21             -0.920742          -0.953421            STANDING
22             -0.854607          -0.882312            STANDING
23             -0.882385          -0.854841            STANDING
24             -0.975992          -0.985084            STANDING
25             -0.974455          -0.975757            STANDING
26             -0.978548          -0.973844            STANDING
27             -0.986493          -0.986741            STANDING
28             -0.985256          -0.986772            STANDING
29             -0.988402          -0.981269            STANDING
...                  ...                ...                 ...
2917           -0.279574          -0.378731    WALKING_UPSTAIRS
2918           -0.292284          -0.407811    WALKING_UPSTAIRS
2919           -0.237156          -0.331832    WALKING_UPSTAIRS
2920           -0.220390          -0.348885    WALKING_UPSTAIRS
2921           -0.258450          -0.345799    WALKING_UPSTAIRS
2922           -0.182228          -0.346912    WALKING_UPSTAIRS
2923           -0.194907          -0.379476    WALKING_UPSTAIRS
2924           -0.277899          -0.351414    WALKING_UPSTAIRS
2925           -0.352964          -0.325547    WALKING_UPSTAIRS
2926           -0.255406          -0.360327    WALKING_UPSTAIRS
2927           -0.278473          -0.404582    WALKING_UPSTAIRS
2928            0.070924          -0.229971  WALKING_DOWNSTAIRS
2929            0.015215          -0.207771  WALKING_DOWNSTAIRS
2930           -0.015270          -0.225313  WALKING_DOWNSTAIRS
2931           -0.119292          -0.213020  WALKING_DOWNSTAIRS
2932           -0.056840          -0.213364  WALKING_DOWNSTAIRS
2933            0.006645          -0.067280  WALKING_DOWNSTAIRS
2934           -0.049004          -0.089838  WALKING_DOWNSTAIRS
2935           -0.025788          -0.163889  WALKING_DOWNSTAIRS
2936            0.006555          -0.198014  WALKING_DOWNSTAIRS
2937           -0.209822          -0.385910    WALKING_UPSTAIRS
2938           -0.235868          -0.370063    WALKING_UPSTAIRS
2939           -0.307131          -0.452012    WALKING_UPSTAIRS
2940           -0.369298          -0.399547    WALKING_UPSTAIRS
2941           -0.340185          -0.424078    WALKING_UPSTAIRS
2942           -0.273191          -0.332141    WALKING_UPSTAIRS
2943           -0.209487          -0.316954    WALKING_UPSTAIRS
2944           -0.236606          -0.377240    WALKING_UPSTAIRS
2945           -0.314763          -0.390201    WALKING_UPSTAIRS
2946           -0.288413          -0.362598    WALKING_UPSTAIRS

[2947 rows x 3 columns]

In [4]:
data['Activity'].replace(['LAYING','STANDING','WALKING','SITTING','WALKING_UPSTAIRS','WALKING_DOWNSTAIRS'],['0','1','00','11','000','111'],inplace=True)

In [5]:
x=data.iloc[:,0:2]
y=data.iloc[:,2]

In [6]:
x

fBodyAccMag-mean()  fBodyAccMag-std()
0              -0.790946          -0.711074
1              -0.954127          -0.959746
2              -0.975650          -0.983784
3              -0.973393          -0.982120
4              -0.977739          -0.978838
5              -0.978002          -0.979876
6              -0.984198          -0.987281
7              -0.991349          -0.990767
8              -0.993556          -0.990614
9              -0.993693          -0.992943
10             -0.993703          -0.993703
11             -0.994000          -0.996011
12             -0.992623          -0.995306
13             -0.988634          -0.987937
14             -0.987386          -0.989505
15             -0.970842          -0.967468
16             -0.862049          -0.855760
17             -0.960538          -0.937976
18             -0.983580          -0.972846
19             -0.938897          -0.925589
20             -0.937565          -0.945013
21             -0.920742          -0.953421
22             -0.854607          -0.882312
23             -0.882385          -0.854841
24             -0.975992          -0.985084
25             -0.974455          -0.975757
26             -0.978548          -0.973844
27             -0.986493          -0.986741
28             -0.985256          -0.986772
29             -0.988402          -0.981269
...                  ...                ...
2917           -0.279574          -0.378731
2918           -0.292284          -0.407811
2919           -0.237156          -0.331832
2920           -0.220390          -0.348885
2921           -0.258450          -0.345799
2922           -0.182228          -0.346912
2923           -0.194907          -0.379476
2924           -0.277899          -0.351414
2925           -0.352964          -0.325547
2926           -0.255406          -0.360327
2927           -0.278473          -0.404582
2928            0.070924          -0.229971
2929            0.015215          -0.207771
2930           -0.015270          -0.225313
2931           -0.119292          -0.213020
2932           -0.056840          -0.213364
2933            0.006645          -0.067280
2934           -0.049004          -0.089838
2935           -0.025788          -0.163889
2936            0.006555          -0.198014
2937           -0.209822          -0.385910
2938           -0.235868          -0.370063
2939           -0.307131          -0.452012
2940           -0.369298          -0.399547
2941           -0.340185          -0.424078
2942           -0.273191          -0.332141
2943           -0.209487          -0.316954
2944           -0.236606          -0.377240
2945           -0.314763          -0.390201
2946           -0.288413          -0.362598

[2947 rows x 2 columns]

In [7]:
y

0         1
1         1
2         1
3         1
4         1
5         1
6         1
7         1
8         1
9         1
10        1
11        1
12        1
13        1
14        1
15        1
16        1
17        1
18        1
19        1
20        1
21        1
22        1
23        1
24        1
25        1
26        1
27        1
28        1
29        1
       ... 
2917    000
2918    000
2919    000
2920    000
2921    000
2922    000
2923    000
2924    000
2925    000
2926    000
2927    000
2928    111
2929    111
2930    111
2931    111
2932    111
2933    111
2934    111
2935    111
2936    111
2937    000
2938    000
2939    000
2940    000
2941    000
2942    000
2943    000
2944    000
2945    000
2946    000
Name: Activity, Length: 2947, dtype: object

In [8]:
from sklearn.model_selection import cross_validate,train_test_split,cross_val_score,cross_val_predict
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [9]:
y1_train=y_train.astype('int')
y1_train

1764      0
2120      0
2715    111
282       0
1841      0
2424      1
882       0
68        0
5         1
634       1
2364    111
361       0
715       0
2489      0
1836      0
2906    111
1813    111
1910     11
1552     11
1445      0
804      11
916       1
2221      1
1171    111
2470      0
371       0
1854      1
2494      0
392       0
2645      0
       ... 
2421      1
2157    111
1663      0
2122      0
2476      0
2310      0
2841      0
2377      0
333      11
1551     11
2609     11
1148      0
384       0
2710    111
1323    111
1967      0
2732      0
752     111
2154      0
74        0
2669      0
2032      0
2898    111
1966      0
2393      1
2873      0
1730     11
2748      0
1139      0
2098      0
Name: Activity, Length: 2357, dtype: int32

In [10]:
from sklearn import preprocessing
minmax=preprocessing.MinMaxScaler(feature_range=(0,1))
minmax.fit(x).transform(x)

array([[0.1338494 , 0.22010741],
       [0.02937104, 0.0303057 ],
       [0.01559064, 0.01195806],
       ...,
       [0.48877336, 0.47490995],
       [0.43873235, 0.46501747],
       [0.45560354, 0.48608557]])

In [11]:
x_train_std=minmax.fit_transform(x_train)
x_test_std=minmax.fit_transform(x_test)
x_train_std

array([[0.00111733, 0.0009091 ],
       [0.01233377, 0.01630746],
       [0.71724227, 0.68175636],
       ...,
       [0.44254176, 0.44316184],
       [0.61687272, 0.55428842],
       [0.00405027, 0.00504004]])

In [12]:
from sklearn import neighbors
clf=neighbors.KNeighborsClassifier()
clf.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [13]:
y_pred=clf.predict(x_test)

In [14]:
y_test=y_test.astype('int')
y_test

533       0
2357    111
2161    111
1520      0
1370      1
1024    111
1398     11
548       0
2072     11
1979    111
29        1
1121      0
1888     11
580     111
1135      0
467       1
881       0
1812    111
2802     11
2319      0
2683      0
2466      0
630       1
2143      0
417     111
785       1
771       1
101       0
1627      0
177       1
       ... 
2738      0
2099      0
1792      0
559       0
2273     11
1701      1
2169    111
286       0
278     111
2836      0
1406     11
2433     11
1819    111
823       0
2621     11
581     111
2657      0
1036      0
1987    111
2359    111
1771      0
2336      0
479       1
1350      0
2766      1
2419      1
1726     11
851       0
1584      0
2803     11
Name: Activity, Length: 590, dtype: int32

In [15]:
y_pred=y_pred.astype('int')
y_pred

array([  1, 111,   0,   0,   0, 111,   1,   0,   0,   0,   0,   0,   1,
       111,   0,   1,   0,   0,  11,   0,   0,   1,   1,   0,   0,   0,
         0,   0,   0,   0,   0,   0, 111,   0,   0,   1,   0,   1,   1,
         1,   0,   0, 111,   0, 111, 111,   1,   0,   0,   1, 111,  11,
         1,  11,   1,  11,   0,   1,   1,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   1,   0,   0,   0,  11, 111,   1,   0,   0, 111,
         0,   0,   0,  11,   1,   0,   0,   0,   0,   0,   0, 111,   1,
         0,   0,   0,   0,   0,   1,   1,   0,   0,   1,   0,   0,   0,
         0,   0,   0, 111,   0,   0,   0,   0,   0,   0,   0, 111,   0,
         0,   0,   0,   1,   0,   0,   0,   0,   0,   0,   1,   0,   0,
         0,   0,   0,   0, 111, 111,   0, 111,   0,   1,   0,   0,   0,
       111,  11,  11, 111,   1,   0,   0,   1,   0,   1,   0,   1,   0,
         1,   0,  11,   0,   0,   0,   0,   1, 111,   0,  11,   0,   0,
         0,   0,   0,   0,   0,  11,   0,   0,   0,   0,   0,   

In [16]:
from sklearn.metrics import accuracy_score,recall_score,roc_auc_score,confusion_matrix
print("Accuracy Score : %f"%(accuracy_score(y_test,y_pred)*100)) #accuracy with knn classifier

Accuracy Score : 63.050847


In [17]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)
lr_acc=cross_val_score(lr,x_train_std,y_train,cv=3,scoring='accuracy',n_jobs=-1)
lr_proba=cross_val_predict(lr,x_train_std,y_train,cv=3,method='predict_proba')
lr_scores=lr_proba[:,1]

C:\Users\Nageswar\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Nageswar\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\Nageswar\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Nageswar\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\Nageswar\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarn

In [18]:
lr_acc #training, validation, testing


array([0.54822335, 0.55470738, 0.550447  ])

In [19]:
y_pred=lr.predict(x_test)

In [20]:
y_test=y_test.astype('int')
y_test

533       0
2357    111
2161    111
1520      0
1370      1
1024    111
1398     11
548       0
2072     11
1979    111
29        1
1121      0
1888     11
580     111
1135      0
467       1
881       0
1812    111
2802     11
2319      0
2683      0
2466      0
630       1
2143      0
417     111
785       1
771       1
101       0
1627      0
177       1
       ... 
2738      0
2099      0
1792      0
559       0
2273     11
1701      1
2169    111
286       0
278     111
2836      0
1406     11
2433     11
1819    111
823       0
2621     11
581     111
2657      0
1036      0
1987    111
2359    111
1771      0
2336      0
479       1
1350      0
2766      1
2419      1
1726     11
851       0
1584      0
2803     11
Name: Activity, Length: 590, dtype: int32

In [21]:
y_pred=y_pred.astype('int')
y_pred

array([  0, 111,   0,   0,   0, 111,   0,   0,   0,   0,   0,   0,   0,
       111,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0, 111,   0,   0,   0,   0,   0,   0,
         0,   0,   0, 111,   0, 111, 111,   0,   0,   0,   0, 111,   1,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0, 111,   0,   0,   0, 111,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 111,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0, 111,   0,   0,   0,   0,   0,   0,   0, 111,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0, 111, 111,   0, 111,   0,   0,   0,   0,   0,
       111,   0,   0, 111,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0, 111,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   

In [22]:
print("Accuracy Score : %f"%(accuracy_score(y_test,y_pred)*100)) #accuracy with logistic regression

Accuracy Score : 57.966102


In [23]:
from sklearn.svm import SVC
svc = SVC(kernel='rbf',probability = True)
svc_classifier = svc.fit(x_train,y_train)

C:\Users\Nageswar\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [24]:
svc_acc = cross_val_score(svc_classifier, x_train_std, y_train, cv=3, scoring="accuracy",  n_jobs=-1)
svc_proba = cross_val_predict(svc_classifier, x_train_std, y_train, cv=3, method='predict_proba')
svc_scores = svc_proba[:, 1]

C:\Users\Nageswar\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\Nageswar\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\Nageswar\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [25]:
y_pred=svc_classifier.predict(x_test)
y_pred=y_pred.astype('int')

In [26]:
print("\nAccuracy score: %f" %(accuracy_score(y_test,y_pred) * 100)) #svc classifier


Accuracy score: 58.644068


In [27]:
from sklearn.ensemble import RandomForestClassifier
rmf = RandomForestClassifier(max_depth=3, random_state=0)
rmf_clf = rmf.fit(x_train, y_train)

C:\Users\Nageswar\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [28]:
rmf_clf_acc = cross_val_score(rmf_clf, x_train_std, y_train, cv=3, scoring="accuracy",  n_jobs=-1)
rmf_proba = cross_val_predict(rmf_clf, x_train_std, y_train, cv=3, method='predict_proba')
rmf_clf_scores = rmf_proba[:, 1]

In [29]:
y_pred=lr.predict(x_test)
y_pred=y_pred.astype('int')

In [30]:
print("\nAccuracy score: %f" %(accuracy_score(y_test,y_pred) * 100)) #random forest classifier


Accuracy score: 57.966102


In [31]:
#Decision Tree Classifier
from sklearn.tree import DecisionTreeClassifier
dtc_clf = DecisionTreeClassifier()
dtc_clf.fit(x_train,y_train)

#Print cross validation score for Decision Tree Classifier
dtc_clf_acc = cross_val_score(dtc_clf, x_train_std, y_train, cv=3, scoring="accuracy",  n_jobs=-1)
dtc_proba = cross_val_predict(dtc_clf, x_train_std, y_train, cv=3, method='predict_proba')
dtc_clf_scores = dtc_proba[:, 1]

In [32]:
y_pred=dtc_clf.predict(x_test)
y_pred=y_pred.astype('int')

In [33]:
print("\nAccuracy score: %f" %(accuracy_score(y_test,y_pred) * 100)) #decision classifier


Accuracy score: 57.796610
